@server=http://localhost:4004
@username=alice
@password=


### VendorMaster
# @name VendorMaster_GET
GET {{server}}/po/VendorMaster
Authorization: Basic {{username}}:{{password}}


### VendorMaster
# @name VendorMaster_POST
POST {{server}}/po/VendorMaster
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "29504063-b687-414d-8777-6ac08f8f9012",
  "vendorCode": "e-29504063",
  "vendorName": "vendorName-29504063",
  "country": "country-29504063",
  "city": "city-29504063",
  "email": "email-29504063",
  "phone": "phone-29504063",
  "status": "status-29504063",
  "createdAt": "2018-08-03T00:00:00.000Z",
  "createdBy": "createdBy-29504063"
}


### VendorMaster
# @name VendorMaster_PATCH
PATCH {{server}}/po/VendorMaster/29504063-b687-414d-8777-6ac08f8f9012
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "29504063-b687-414d-8777-6ac08f8f9012",
  "vendorCode": "e-29504063",
  "vendorName": "vendorName-29504063",
  "country": "INDIA",
  "city": "MANALI",
  "email": "email-29504063",
  "phone": "phone-29504063",
  "status": "status-29504063",
  "createdAt": "2018-08-03T00:00:00.000Z",
  "createdBy": "createdBy-29504063"
}


### VendorMaster
# @name VendorMaster_DELETE
DELETE {{server}}/po/VendorMaster/29504063-b687-414d-8777-6ac08f8f9012
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### MasterMaterials
# @name MasterMaterials_GET
GET {{server}}/po/MasterMaterials
Authorization: Basic {{username}}:{{password}}


### MasterMaterials
# @name MasterMaterials_POST
POST {{server}}/po/MasterMaterials
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "1952396f-9e38-4fb6-bec9-837bd343b737",
  "materialCode": "materialCode-1952396",
  "materialName": "materialName-1952396",
  "materialType": "materialType-1952396",
  "baseUnit": "it-1952396",
  "materialGroup": "materialGroup-1952396",
  "price": 64918305.51,
  "currency": "52396",
  "status": "status-1952396",
  "createdAt": "2021-05-28T00:00:00.000Z"
}


### MasterMaterials
# @name MasterMaterials_PATCH
PATCH {{server}}/po/MasterMaterials/1952396f-9e38-4fb6-bec9-837bd343b737
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "1952396f-9e38-4fb6-bec9-837bd343b737",
  "materialCode": "materialCode-1952396",
  "materialName": "materialName-1952396",
  "materialType": "materialType-1952396",
  "baseUnit": "it-1952396",
  "materialGroup": "materialGroup-1952396",
  "price": 64918305.51,
  "currency": "52396",
  "status": "status-1952396",
  "createdAt": "2021-05-28T00:00:00.000Z"
}


### MasterMaterials
# @name MasterMaterials_DELETE
DELETE {{server}}/po/MasterMaterials/1952396f-9e38-4fb6-bec9-837bd343b737
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### PurchaseOrders
# @name PurchaseOrders_GET
GET {{server}}/po/PurchaseOrders
Authorization: Basic {{username}}:{{password}}


### PurchaseOrders Drafts GET
# @name PurchaseOrders_Drafts_GET
GET {{server}}/po/PurchaseOrders?$filter=(IsActiveEntity eq false)
Authorization: Basic {{username}}:{{password}}


### PurchaseOrders Draft POST
# @name PurchaseOrders_Draft_POST
POST {{server}}/po/PurchaseOrders
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "poNumber": "poNumber-15908250",
  "vendor": {
    "ID": "29504063-b687-414d-8777-6ac08f8f9012"
  },
  "orderDate": "2006-02-08",
  "deliveryDate": "2003-03-20",
  "totalAmount": 3939767000889.14,
  "currency": "08250",
  "status": "status-15908250",
  "approvalStatus": "approvalStatus-15908250",
  "items": [
    {
      "ID": "78844043-592f-4051-a60c-a11a5a27962e",
      "material": {
        "ID": "1952396f-9e38-4fb6-bec9-837bd343b737"
      },
      "quantity": 89380719.49,
      "unitPrice": 87024611.04,
      "totalPrice": 1630008737529.19,
      "deliveryDate": "2012-01-25"
    },
    {
      "ID": "7884405b-17ef-45fd-92dc-ea8f4b913b72",
      "material": {
        "ID": "1952396f-9e38-4fb6-bec9-837bd343b737"
      },
      "quantity": 11897315.85,
      "unitPrice": 9489591.47,
      "totalPrice": 1602858950894.24,
      "deliveryDate": "2004-10-28"
    }
  ]
}


### Result from POST request above
@draftID={{PurchaseOrders_Draft_POST.response.body.$.ID}}


### PurchaseOrders Draft PATCH
# @name PurchaseOrders_Draft_Patch
PATCH {{server}}/po/PurchaseOrders(ID={{draftID}},IsActiveEntity=false)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "poNumber": "poNumber-15908250",
  "vendor": {
    "ID": "29504063-b687-414d-8777-6ac08f8f9012"
  },
  "orderDate": "2006-02-08",
  "deliveryDate": "2003-03-20",
  "totalAmount": 3939767000889.14,
  "currency": "08250",
  "status": "status-15908250",
  "approvalStatus": "approvalStatus-15908250",
  "items": [
    {
      "ID": "78844043-592f-4051-a60c-a11a5a27962e",
      "material": {
        "ID": "1952396f-9e38-4fb6-bec9-837bd343b737"
      },
      "quantity": 89380719.49,
      "unitPrice": 87024611.04,
      "totalPrice": 1630008737529.19,
      "deliveryDate": "2012-01-25"
    },
    {
      "ID": "7884405b-17ef-45fd-92dc-ea8f4b913b72",
      "material": {
        "ID": "1952396f-9e38-4fb6-bec9-837bd343b737"
      },
      "quantity": 11897315.85,
      "unitPrice": 9489591.47,
      "totalPrice": 1602858950894.24,
      "deliveryDate": "2004-10-28"
    }
  ]
}


### PurchaseOrders Draft Prepare
# @name PurchaseOrders_Draft_Prepare
POST {{server}}/po/PurchaseOrders(ID={{draftID}},IsActiveEntity=false)/DashboardService.draftPrepare
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### PurchaseOrders Draft Activate
# @name PurchaseOrders_Draft_Activate
POST {{server}}/po/PurchaseOrders(ID={{draftID}},IsActiveEntity=false)/DashboardService.draftActivate
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### POItems
# @name POItems_GET
GET {{server}}/po/POItems
Authorization: Basic {{username}}:{{password}}


### POItems
# @name POItems_POST
POST {{server}}/po/POItems
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "78844043-592f-4051-a60c-a11a5a27962e",
  "material": {
    "ID": "1952396f-9e38-4fb6-bec9-837bd343b737"
  },
  "quantity": 89380719.49,
  "unitPrice": 87024611.04,
  "totalPrice": 1630008737529.19,
  "deliveryDate": "2012-01-25"
}


### POItems
# @name POItems_PATCH
PATCH {{server}}/po/POItems/78844043-592f-4051-a60c-a11a5a27962e
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "78844043-592f-4051-a60c-a11a5a27962e",
  "material": {
    "ID": "1952396f-9e38-4fb6-bec9-837bd343b737"
  },
  "quantity": 89380719.49,
  "unitPrice": 87024611.04,
  "totalPrice": 1630008737529.19,
  "deliveryDate": "2012-01-25"
}


### POItems
# @name POItems_DELETE
DELETE {{server}}/po/POItems/78844043-592f-4051-a60c-a11a5a27962e
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### GoodsReceipt
# @name GoodsReceipt_GET
GET {{server}}/po/GoodsReceipt
Authorization: Basic {{username}}:{{password}}


### GoodsReceipt
# @name GoodsReceipt_POST
POST {{server}}/po/GoodsReceipt
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "22476732-52c2-4cab-b3d5-c204098f8071",
  "grNumber": "grNumber-22476732",
  "purchaseOrder": {
    "ID": "15908250-3c2b-44da-9255-0c0a8069c9a8"
  },
  "receiptDate": "2014-04-13",
  "status": "status-22476732",
  "isOverdue": true,
  "quantity": 17181380.35,
  "remarks": "remarks-22476732"
}


### GoodsReceipt
# @name GoodsReceipt_PATCH
PATCH {{server}}/po/GoodsReceipt/22476732-52c2-4cab-b3d5-c204098f8071
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "22476732-52c2-4cab-b3d5-c204098f8071",
  "grNumber": "grNumber-22476732",
  "purchaseOrder": {
    "ID": "15908250-3c2b-44da-9255-0c0a8069c9a8"
  },
  "receiptDate": "2014-04-13",
  "status": "status-22476732",
  "isOverdue": true,
  "quantity": 17181380.35,
  "remarks": "remarks-22476732"
}


### GoodsReceipt
# @name GoodsReceipt_DELETE
DELETE {{server}}/po/GoodsReceipt/22476732-52c2-4cab-b3d5-c204098f8071
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### InvoiceReport
# @name InvoiceReport_GET
GET {{server}}/po/InvoiceReport
Authorization: Basic {{username}}:{{password}}


### InvoiceReport
# @name InvoiceReport_POST
POST {{server}}/po/InvoiceReport
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "22471573-f768-4f8d-8e40-9d9b7dce5d89",
  "invoiceNumber": "voiceNumber-22471573",
  "purchaseOrder": {
    "ID": "15908250-3c2b-44da-9255-0c0a8069c9a8"
  },
  "vendor": {
    "ID": "29504063-b687-414d-8777-6ac08f8f9012"
  },
  "invoiceDate": "2016-05-02",
  "dueDate": "2005-05-04",
  "totalAmount": 8250209626438.09,
  "currency": "71573",
  "status": "status-22471573",
  "verificationStatus": "verificationStatus-22471573",
  "paymentStatus": "paymentStatus-22471573"
}


### InvoiceReport
# @name InvoiceReport_PATCH
PATCH {{server}}/po/InvoiceReport/22471573-f768-4f8d-8e40-9d9b7dce5d89
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "22471573-f768-4f8d-8e40-9d9b7dce5d89",
  "invoiceNumber": "voiceNumber-22471573",
  "purchaseOrder": {
    "ID": "15908250-3c2b-44da-9255-0c0a8069c9a8"
  },
  "vendor": {
    "ID": "29504063-b687-414d-8777-6ac08f8f9012"
  },
  "invoiceDate": "2016-05-02",
  "dueDate": "2005-05-04",
  "totalAmount": 8250209626438.09,
  "currency": "71573",
  "status": "status-22471573",
  "verificationStatus": "verificationStatus-22471573",
  "paymentStatus": "paymentStatus-22471573"
}


### InvoiceReport
# @name InvoiceReport_DELETE
DELETE {{server}}/po/InvoiceReport/22471573-f768-4f8d-8e40-9d9b7dce5d89
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### InvoicePrinting
# @name InvoicePrinting_GET
GET {{server}}/po/InvoicePrinting
Authorization: Basic {{username}}:{{password}}


### InvoicePrinting
# @name InvoicePrinting_POST
POST {{server}}/po/InvoicePrinting
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "70238172-7062-40a4-99dd-f1f975ad53d1",
  "printID": "printID-7023817",
  "invoice": {
    "ID": "22471573-f768-4f8d-8e40-9d9b7dce5d89"
  },
  "printDate": "2011-10-23T00:00:00.000Z",
  "printedBy": "printedBy-7023817",
  "copies": 7
}


### InvoicePrinting
# @name InvoicePrinting_PATCH
PATCH {{server}}/po/InvoicePrinting/70238172-7062-40a4-99dd-f1f975ad53d1
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "70238172-7062-40a4-99dd-f1f975ad53d1",
  "printID": "printID-7023817",
  "invoice": {
    "ID": "22471573-f768-4f8d-8e40-9d9b7dce5d89"
  },
  "printDate": "2011-10-23T00:00:00.000Z",
  "printedBy": "printedBy-7023817",
  "copies": 7
}


### InvoicePrinting
# @name InvoicePrinting_DELETE
DELETE {{server}}/po/InvoicePrinting/70238172-7062-40a4-99dd-f1f975ad53d1
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### AuditReport
# @name AuditReport_GET
GET {{server}}/po/AuditReport
Authorization: Basic {{username}}:{{password}}


### AuditReport
# @name AuditReport_POST
POST {{server}}/po/AuditReport
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "53261299-2e89-4bf5-94b8-4154f4699222",
  "auditID": "auditID-5326129",
  "auditType": "auditType-5326129",
  "auditDate": "2001-05-30",
  "auditor": "auditor-5326129",
  "findings": "findings-5326129",
  "status": "status-5326129",
  "lastRun": "2019-09-14T00:00:00.000Z"
}


### AuditReport
# @name AuditReport_PATCH
PATCH {{server}}/po/AuditReport/53261299-2e89-4bf5-94b8-4154f4699222
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "53261299-2e89-4bf5-94b8-4154f4699222",
  "auditID": "auditID-5326129",
  "auditType": "auditType-5326129",
  "auditDate": "2001-05-30",
  "auditor": "auditor-5326129",
  "findings": "findings-5326129",
  "status": "status-5326129",
  "lastRun": "2019-09-14T00:00:00.000Z"
}


### AuditReport
# @name AuditReport_DELETE
DELETE {{server}}/po/AuditReport/53261299-2e89-4bf5-94b8-4154f4699222
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### ErrorLogs
# @name ErrorLogs_GET
GET {{server}}/po/ErrorLogs
Authorization: Basic {{username}}:{{password}}


### ErrorLogs
# @name ErrorLogs_POST
POST {{server}}/po/ErrorLogs
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "18475586-5ec2-4b3f-84d8-e0cbbd66fa1c",
  "errorCode": "errorCode-18475586",
  "errorMessage": "errorMessage-18475586",
  "severity": "severity-18475586",
  "occurredAt": "2014-10-12T00:00:00.000Z",
  "module": "module-18475586",
  "requiresAttention": true,
  "resolvedAt": "2006-12-06T00:00:00.000Z",
  "resolvedBy": "resolvedBy-18475586"
}


### ErrorLogs
# @name ErrorLogs_PATCH
PATCH {{server}}/po/ErrorLogs/18475586-5ec2-4b3f-84d8-e0cbbd66fa1c
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "18475586-5ec2-4b3f-84d8-e0cbbd66fa1c",
  "errorCode": "errorCode-18475586",
  "errorMessage": "errorMessage-18475586",
  "severity": "severity-18475586",
  "occurredAt": "2014-10-12T00:00:00.000Z",
  "module": "module-18475586",
  "requiresAttention": true,
  "resolvedAt": "2006-12-06T00:00:00.000Z",
  "resolvedBy": "resolvedBy-18475586"
}


### ErrorLogs
# @name ErrorLogs_DELETE
DELETE {{server}}/po/ErrorLogs/18475586-5ec2-4b3f-84d8-e0cbbd66fa1c
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### SecuritySettings
# @name SecuritySettings_GET
GET {{server}}/po/SecuritySettings
Authorization: Basic {{username}}:{{password}}


### SecuritySettings
# @name SecuritySettings_POST
POST {{server}}/po/SecuritySettings
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "14472128-efcb-4409-8b4d-1dcfc32ba06f",
  "settingName": "settingName-14472128",
  "settingValue": "settingValue-14472128",
  "isActive": true,
  "lastModified": "2006-07-06T00:00:00.000Z",
  "modifiedBy": "modifiedBy-14472128"
}


### SecuritySettings
# @name SecuritySettings_PATCH
PATCH {{server}}/po/SecuritySettings/14472128-efcb-4409-8b4d-1dcfc32ba06f
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "14472128-efcb-4409-8b4d-1dcfc32ba06f",
  "settingName": "settingName-14472128",
  "settingValue": "settingValue-14472128",
  "isActive": true,
  "lastModified": "2006-07-06T00:00:00.000Z",
  "modifiedBy": "modifiedBy-14472128"
}


### SecuritySettings
# @name SecuritySettings_DELETE
DELETE {{server}}/po/SecuritySettings/14472128-efcb-4409-8b4d-1dcfc32ba06f
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### approvePO
# @name approvePO_POST
POST {{server}}/po/approvePO
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "poId": "45050706-be24-4b0f-ae4b-7620a6b14c2d"
}
